sokothai/src/Entity/Event.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\BooleanFilter;
use App\Repository\EventRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 * @ApiResource(
 *     attributes={
            "order"={"createdAt":"ASC"},
 *     },
 *     normalizationContext={"groups"={"read:event"}},
 *     collectionOperations={
 *      "get",
 *      "post"={
 *          "security"="is_granted('IS_AUTHENTICATED_FULLY')",
            "controller"=App\Controller\Api\EventCreatorController::class
 *       }
 *      },
 *     itemOperations={
 *       "get",
 *       "put"={
            "security"="is_granted('IS_AUTHENTICATED_FULLY')",
 *       },
 *      "delete"={
            "security"="is_granted('IS_AUTHENTICATED_FULLY')",
 *       },
 *     }
 * )
 * @ApiFilter(BooleanFilter::class,
 *     properties={"isActived"})
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"read:event"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Groups({"read:event"})
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"read:event"})
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"read:event"})
     */
    private $url_facebook;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="boolean")
     * @Groups({"read:event"})
     */
    private $isActived = true;

    public function __construct() {
        $this->createdAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUrlFacebook(): ?string
    {
        return $this->url_facebook;
    }

    public function setUrlFacebook(?string $url_facebook): self
    {
        $this->url_facebook = $url_facebook;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getIsActived(): ?bool
    {
        return $this->isActived;
    }

    public function setIsActived(bool $isActived): self
    {
        $this->isActived = $isActived;

        return $this;
    }
}

sokothai/templates/homepage/index.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <header xmlns="http://www.w3.org/1999/html" id="header">
        <div class="container">
            <nav class="navbar navbar-expand-lg">
                <a class="navbar-brand">
                    <img src="{{ asset('build/images/logo_white.svg') }}" alt="Logo Sokothai" class="logo-nav">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <img src="{{ asset('build/images/dots-menu.svg') }}" alt="Icon menu" class="nav-icon-menu">
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link nav-link-custom" href="#formules">Nos formules</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-link-custom" href="#events">Événements</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-link-custom" href="#localisation">Le lieux</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-link-custom" href="#contact">Contact</a>
                        </li>
                        {% if is_granted('ROLE_USER') %}
                            <li class="nav-item">
                                <a class="nav-link nav-link-custom" href="{{ path('event_list') }}">Admin</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link nav-link-custom text-danger" href="{{ path('app_logout') }}">Déconnexion</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link nav-link-custom" href="https://www.facebook.com/soko.thai/">
                                <img src="{{ asset('build/images/facebook-app-symbol.svg') }}" alt="Logo facebook Sokothai" class="nav-facebook-logo">
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            <div class="block-title">
                <h1>Spécialité Asiatique</h1>
                <p>Buffet à volonté</p>
                <a href="{{ asset('build/images/menu.jpg') }}" class="header-btn-cta">Notre carte</a>
            </div>
        </div>
    </header>

    <section class="formules" id="formules">
        <div class="container">
            <div class="header-formules">
                <h3>Nos Formules</h3>
                <p>Découvrez nos formules</p>
            </div>
            <div class="row">
                <div class="col-8 mx-auto">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="block-formules">
                                <h4>Sur place</h4>
                                <div class="row-price">
                                    <div class="block-price">
                                        <span class="block-price-time">Midi</span>
                                        <span class="block-price-number">12,90 €</span>
                                    </div>
                                    <div class="block-price">
                                        <span class="block-price-time">Soir</span>
                                        <span class="block-price-number">17,90 €</span>
                                    </div>
                                </div>
                                <small>*Boisson non compris, prix spécial enfant à partir de 5,90 €</small>

                            </div>


                        </div>
                        <div class="col-lg-6">
                            <div class="block-formules">
                                <h4>À emporter</h4>
                                <p>Tous les jours, en passant par le téléphone au <a class="number-telephone" href="tel:+330320558867">03 20 55 88 67</a> ou en envoyant un message via Messenger</p>
                                <a href="{{ asset('build/images/menu.jpg') }}" class="btn-formules-carte">Notre carte</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>

    <section class="follow-facebook">
        <div class="container">
            <p>Suivez-nous sur facebook afin d'etre informer de nos actualités</p>
            <a href="https://www.facebook.com/soko.thai/" class="btn-follow-facebook">
                Facebook<span><i class="fa fa-chevron-right"></i></span>
            </a>
        </div>
    </section>

    <section class="events" id="events">
        <div class="container">
            <div class="header-events">
                <h3>Événements</h3>
                <p>Retrouvez-nous dans nos différentes soirées à thème</p>
            </div>
            {% if events %}
                {% for event in events %}
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <a href="{{ event.urlFacebook }}" class="block-event">
                            <div class="block-event-information">
                                <time>{{ event.createdAt|format_datetime(locale='fr',pattern="EEE dd LLL YYYY")|upper }}</time>
                                <h4>{{ event.name }}</h4>
                                <span>{{ event.createdAt|date('H:i') }}</span>
                            </div>
                            <div class="block-event-icon">
                                <div class="circle">
                                    <i class="fas fa-chevron-right"></i>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <div class="block-event">
                            <p class="block-event-empty">Pas d'évènement pour le moment</p>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </section>

    <section id="localisation" class="localisation">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div id="map" class="map">

                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="block-adress">
                        <h3>Adresse</h3>
                        <p>11, rue Jules Guedes</br>
                        59700 <span>MARCQ EN BAROEUL</span></br>
                        à coté du complexe cinéma</p>
                    </div>
                </div>
            </div>

        </div>
    </section>

    <section id="contact" class="contact">
        <div class="container">
            <div class="header-contact">
                <h3>Contact</h3>
                <p>Une question? N'hesitez pas à nous écrire, nous vous repondrons le plus rapidement possible</p>
            </div>

            <div class="row">
                <div class="col-lg-10 mx-auto">
                    {{ form_start(form, {'attr': {'id': 'form-contact'}, 'action': path('ajax-mail')}) }}
                        <div class="form-group">
                            {{ form_widget(form.name,{'attr': {'data-name': 'name'}}) }}
                            {{ form_errors(form.name) }}
                        </div>
                        <div class="form-group">
                            {{ form_widget(form.mail,{'attr': {'data-name': 'mail'}}) }}
                            {{ form_errors(form.mail) }}
                        </div>
                        <div class="form-group">
                            {{ form_widget(form.subject,{'attr': {'data-name': 'subject'}}) }}
                            {{ form_errors(form.subject) }}
                        </div>
                        <div class="form-group">
                            {{ form_widget(form.text,{'attr': {'data-name': 'text'}}) }}
                            {{ form_errors(form.text) }}
                        </div>
                        <input type="submit" class="btn-envoyer mt-3" value="Envoyer">
                    {{ form_end(form) }}
                </div>
            </div>

        </div>
    </section>

    <!-- footer -->
    <footer class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-md-6">
                    <h5>Information</h5>
                    <img class="logo-footer" src="{{ asset('build/images/logo_white.svg') }}" alt="logo">
                    <p>
                        Restautant asiatique<br>
                        Dans un cadre chalereux<br>
                        Buffet à volonté
                    </p>
                </div>
                <div class="col-xl-3 col-md-6">
                    <h5>Horaires d'ouverture</h5>
                    <p>
                        Lundi Fermé<br>
                        Mardi 12h00-14h30 et 19h00-22h00<br>
                        Mercrdi 12h00-14h30 et 19h00-22h00<br>
                        Jeudi 12h00-14h30 et 19h00-22h00<br>
                        Vendredi 12h00-14h30 et 19h00-22h00<br>
                        Samedi 12h00-14h30 et 19h00-22h00<br>
                        Dimanche 12h00 à 14h30<br>
                    </p>
                </div>
                <div class="col-xl-3 col-md-6 block-footer-right">
                    <h5>Suivez-nous</h5>
                    <p>
                        <a href="https://www.facebook.com/soko.thai/" target="_blank">
                            <img class="footer-size-logo" src="{{ asset('build/images/logo_footer_facebook.svg') }}" alt="logo facebook">
                        </a>
                        <a href="https://www.instagram.com/soko.thai/" target="_blank">
                            <img class="footer-size-logo" src="{{ asset('build/images/logo_footer_instagram.svg') }}" alt="logo instagram">
                        </a>
                    </p>
                </div>
                <div class="col-xl-3 col-md-6 block-footer-right">
                    <h5>Contact</h5>
                    <p>
                        11, rue Jules Guedes<br>
                        59700 MARCQ EN BAROEUL<br>
                        03 20 55 88 67<br>
                    </p>
                    <a href="mailto:soko.thai.contact@gmail.com" class="footer-link-mail">soko.thai.contact@gmail.com</a>
                </div>
            </div>
        </div>
    </footer>
    <div class="footer-bottom">
        <p>
            Dev with <i class="fas fa-heart"></i> by <a href="http://ampueropierre.fr/">Ampuero Pierre</a> | <a
                    href="{{ path('app_login') }}">Connexion</a>
        </p>
    </div>
    <a class="scroll-top" href="#header" style="display: none">
        <i class="fas fa-angle-up fa-2x"></i>
    </a>
{% endblock %}